trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Install Node.js
- task: UseNode@1
  inputs:
    version: '16.x'  # Specify the Node.js version.
  displayName: 'Install Node.js'

# Step 2: Install Dependencies
- script: npm install
  displayName: 'Install Dependencies'

# Step 3: Run Login Tests
- script: npm test
  displayName: 'Run Login Function Tests'

# Step 4: (Optional) Deploy Application
# Add deployment steps if you want to deploy this app somewhere.
