# Trigger the pipeline when changes are pushed to the 'main' branch.
trigger:
- main

# Specify the type of agent (virtual machine) to run the pipeline on.
pool:
  vmImage: 'ubuntu-latest'  # Using Ubuntu as the agent OS.

# Define the steps to build, test, and deploy the application.
steps:
# Step 1: Install Node.js
- task: UseNode@1
  inputs:
    version: '16.x'  # Specify the Node.js version.
  displayName: 'Install Node.js'

# Step 2: Install Application Dependencies
- script: npm install  # Installs all dependencies listed in package.json.
  displayName: 'Install Dependencies'

# Step 3: Run Automated Tests
- script: npm test  # Runs unit tests. Here it is running against tests/app.test.js.
  displayName: 'Run Automated Test'

# Step 4: Build the Application
- script: npm run build  # Builds the app (common for React/Angular/Node apps).
  displayName: 'Build the Application'

# Step 5: Deploy to Azure App Service
- task: AzureRmWebAppDeployment@4
  inputs:
    appType: 'webApp'
    packageForLinux: '$(System.DefaultWorkingDirectory)/dist'  # Adjust for your build output folder.
    azureSubscription: 'MyAzureSubscription'  # Service connection to Azure.
    WebAppName: 'MyNodeApp'  # Name of your App Service.
  displayName: 'Deploy to Azure App Service'
